name: Daily Lunar Card Generator

on:
  schedule:
    # 上海时区每日凌晨00:30执行 (UTC时间16:30)
    - cron: '30 16 * * *'
  # 允许手动触发
  workflow_dispatch:

permissions:  # 关键：添加仓库内容写入权限
  contents: write

jobs:
  generate-and-deploy:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai  # 设置时区为上海

    steps:
      # 1. 检出代码
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 获取完整历史记录
          token: ${{ secrets.GITHUB_TOKEN }}

      # 2. 设置 Node.js v22
      - name: Setup Node.js v22
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'

      # 3. 安装 FFmpeg
      - name: Install FFmpeg
        run: sudo apt-get install -y ffmpeg

      # 4. 安装依赖
      - name: Install dependencies
        run: npm ci

      # 5. 设置环境变量
      - name: Setup environment variables
        env:
          EMAIL_SMTP_USER: ${{ secrets.EMAIL_SMTP_USER }}
          EMAIL_SMTP_TOKEN: ${{ secrets.EMAIL_SMTP_TOKEN }}
          EMAIL_SMTP_HOST: ${{ secrets.EMAIL_SMTP_HOST }}
          EMAIL_SMTP_PORT: ${{ secrets.EMAIL_SMTP_PORT }}
          EMAIL_RECEIVER: ${{ secrets.EMAIL_RECEIVER }}
          OSS_ACCESS_KEY: ${{ secrets.OSS_ACCESS_KEY }}
          OSS_SECRET_KEY: ${{ secrets.OSS_SECRET_KEY }}
          OSS_REGION_NAME: ${{ secrets.OSS_REGION_NAME }}
          OSS_BUCKET_NAME: ${{ secrets.OSS_BUCKET_NAME }}
          OSS_DIR_PATH: ${{ secrets.OSS_DIR_PATH }}
        run: |
          echo "EMAIL_SMTP_USER=$EMAIL_SMTP_USER" >> $GITHUB_ENV
          echo "EMAIL_SMTP_TOKEN=$EMAIL_SMTP_TOKEN" >> $GITHUB_ENV
          echo "EMAIL_SMTP_HOST=$EMAIL_SMTP_HOST" >> $GITHUB_ENV
          echo "EMAIL_SMTP_PORT=$EMAIL_SMTP_PORT" >> $GITHUB_ENV
          echo "EMAIL_RECEIVER=$EMAIL_RECEIVER" >> $GITHUB_ENV
          echo "OSS_ACCESS_KEY=$OSS_ACCESS_KEY" >> $GITHUB_ENV
          echo "OSS_SECRET_KEY=$OSS_SECRET_KEY" >> $GITHUB_ENV
          echo "OSS_REGION_NAME=$OSS_REGION_NAME" >> $GITHUB_ENV
          echo "OSS_BUCKET_NAME=$OSS_BUCKET_NAME" >> $GITHUB_ENV

      # 6. 执行生成脚本
      - name: Generate daily card
        run: node index.js

      # 7. 自动提交所有变更到 master 分支 (无论成功与否)
      - name: Commit changes
        if: always()  # 无论之前步骤成功或失败都执行
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add .
          git diff-index --quiet HEAD || git commit -m "Auto-commit: Daily lunar update [skip ci]"
          git push origin HEAD:master